NUM_GPUS: [0,1]
MODEL: 'full_eval'
OUTPUT_DIR: './output'
TEST:
  LOAD_LIDAR_TO_CAM_WEIGHTS: "/lidar2cam_new_loss/saved_models"
  LOAD_PIX2PIX_WEIGHTS: "/pix2pix/pix2pix_saved_models"
  LOAD_BASELINE_WEIGHTS: "/baseline/saved_models"
  INPUT_DIR: "/home/tiago/Documents/Inputs/TEST"
  SEGMENTED_LIDAR_ROOT: "/home/tiago/Documents/Inputs/TEST/2011_09_26_drive_0086_sync_lid"
  SEGMENTED_CAMERA_ROOT: "/home/tiago/Documents/Inputs/TEST/2011_09_26_drive_0086_sync_cam"
  CLOUD_ROOT: "/SPACE/DATA/KITTI_Data/KITTI_labeledPC_with_BBs/2011_09_26"
  RGB_ROOT: "/SPACE/DATA/KITTI_Data/KITTI_raw_data/kitti/2011_09_26"
  RESULT_SAVE_PATH: "/eval"
  EVAL_EPOCH: 0


