NUM_GPUS: 2
TEST:
  LOAD_LIDAR_TO_CAM_WEIGHTS: "/home/fatih/my_git/sensorgan/outputs/saved_models/4.pth"
  LOAD_PIX2PIX_WEIGHTS: "/home/fatih/my_git/sensorgan/outputs/pipx_yedk/normalized_0.9true_input1d_nonnormal_55"
